import type { Book, Author, Publisher } from "@/types";

export const booksData: Book[] = [
  {
    id: 1,
    title: "সহজ আরবি বক্তব্য (الْخُطَبُ الْمُيَسَّرَةُ)",
    author: "মুহাম্মাদ ইলিয়াস রিফায়ী",
    price: "৪৬৮৳",
    oldPrice: "৭২০৳",
    discount: "35",
    image: "/book_cover_img/book_cover_img (0).webp",
  },
  {
    id: 2,
    title: "গণআকাঙ্ক্ষা থেকে গণঅভ্যুত্থান: (ছাত্রদলের...)",
    author: "কাজী জিয়া উদ্দিন বাসিত",
    price: "৫৬২৳",
    oldPrice: "৭৫০৳",
    discount: "25",
    image: "/book_cover_img/book_cover_img (1).webp",
  },
  {
    id: 3,
    title: "আল মুকাদ্দিমাতুল জাযারিয়্যাহ (বাংলা)",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: "৫০৳",
    oldPrice: "১০০৳",
    discount: "50",
    image: "/book_cover_img/book_cover_img (2).webp",
  },
  {
    id: 4,
    title: "ঈমানী হৃদয়ের ইবাদতনামা",
    author: "শায়খ ড. আলী বিন আব্দুর...",
    price: "১০৫৳",
    oldPrice: "১৪০৳",
    discount: "25",
    image: "/book_cover_img/book_cover_img (3).webp",
  },
  {
    id: 5,
    title: "আল-মুকাদ্দিমাতুল জাযারিয়্যাহ",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: "৫৫৳",
    oldPrice: "১০০৳",
    discount: "45",
    image: "/book_cover_img/book_cover_img (4).webp",
  },
  {
    id: 6,
    title: "সময়ের দ্বৈততা",
    author: "মোহাম্মদ ছাজ ইউসুফ",
    price: "৫২০৳",
    oldPrice: "৬৫০৳",
    discount: "20",
    image: "/book_cover_img/book_cover_img (5).webp",
  },
  {
    id: 7,
    title: "আল-মুকাদ্দিমাতুল জাযারিয়্যাহ",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: " ৭৭৳",
    oldPrice: "১৪০৳",
    discount: "45",
    image: "/book_cover_img/book_cover_img (6).webp",
  },
  {
    id: 8,
    title: "বেরেলির ইমাম",
    author: "মাকতাবাতুদ দাওয়াহ টিম",
    price: "২০০৳",
    image: "/book_cover_img/book_cover_img (7).webp",
  },
  {
    id: 11,
    title: "সহজ আরবি বক্তব্য (الْخُطَبُ الْمُيَسَّرَةُ)",
    author: "মুহাম্মাদ ইলিয়াস রিফায়ী",
    price: "৪৬৮৳",
    oldPrice: "৭২০৳",
    discount: "35",
    image: "/book_cover_img/book_cover_img (8).webp",
  },
  {
    id: 21,
    title: "গণআকাঙ্ক্ষা থেকে গণঅভ্যুত্থান: (ছাত্রদলের...)",
    author: "কাজী জিয়া উদ্দিন বাসিত",
    price: "৫৬২৳",
    oldPrice: "৭৫০৳",
    discount: "25",
    image: "/book_cover_img/book_cover_img (9).webp",
  },
  {
    id: 31,
    title: "আল মুকাদ্দিমাতুল জাযারিয়্যাহ (বাংলা)",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: "৫০৳",
    oldPrice: "১০০৳",
    discount: "50",
    image: "/book_cover_img/book_cover_img (10).webp",
  },
  {
    id: 41,
    title: "ঈমানী হৃদয়ের ইবাদতনামা",
    author: "শায়খ ড. আলী বিন আব্দুর...",
    price: "১০৫৳",
    oldPrice: "১৪০৳",
    discount: "25",
    image: "/book_cover_img/book_cover_img (11).webp",
  },
  {
    id: 51,
    title: "আল-মুকাদ্দিমাতুল জাযারিয়্যাহ",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: "৫৫৳",
    oldPrice: "১০০৳",
    discount: "45",
    image: "/book_cover_img/book_cover_img (12).webp",
  },
  {
    id: 61,
    title: "সময়ের দ্বৈততা",
    author: "মোহাম্মদ ছাজ ইউসুফ",
    price: "৫২০৳",
    oldPrice: "৬৫০৳",
    discount: "20",
    image: "/book_cover_img/book_cover_img (13).webp",
  },
  {
    id: 71,
    title: "আল-মুকাদ্দিমাতুল জাযারিয়্যাহ",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: " ৭৭৳",
    oldPrice: "১৪০৳",
    discount: "45",
    image: "/book_cover_img/book_cover_img (14).webp",
  },
  {
    id: 81,
    title: "বেরেলির ইমাম",
    author: "মাকতাবাতুদ দাওয়াহ টিম",
    price: "২০০৳",
    image: "/book_cover_img/book_cover_img (15).webp",
  },
  {
    id: 12,
    title: "সহজ আরবি বক্তব্য (الْخُطَبُ الْمُيَسَّرَةُ)",
    author: "মুহাম্মাদ ইলিয়াস রিফায়ী",
    price: "৪৬৮৳",
    oldPrice: "৭২০৳",
    discount: "35",
    image: "/book_cover_img/book_cover_img (16).webp",
  },
  {
    id: 22,
    title: "গণআকাঙ্ক্ষা থেকে গণঅভ্যুত্থান: (ছাত্রদলের...)",
    author: "কাজী জিয়া উদ্দিন বাসিত",
    price: "৫৬২৳",
    oldPrice: "৭৫০৳",
    discount: "25",
    image: "/book_cover_img/book_cover_img (17).webp",
  },
  {
    id: 32,
    title: "আল মুকাদ্দিমাতুল জাযারিয়্যাহ (বাংলা)",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: "৫০৳",
    oldPrice: "১০০৳",
    discount: "50",
    image: "/book_cover_img/book_cover_img (18).webp",
  },
  {
    id: 42,
    title: "ঈমানী হৃদয়ের ইবাদতনামা",
    author: "শায়খ ড. আলী বিন আব্দুর...",
    price: "১০৫৳",
    oldPrice: "১৪০৳",
    discount: "25",
    image: "/book_cover_img/book_cover_img (19).webp",
  },
  {
    id: 52,
    title: "আল-মুকাদ্দিমাতুল জাযারিয়্যাহ",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: "৫৫৳",
    oldPrice: "১০০৳",
    discount: "45",
    image: "/book_cover_img/book_cover_img (20).webp",
  },
  {
    id: 62,
    title: "সময়ের দ্বৈততা",
    author: "মোহাম্মদ ছাজ ইউসুফ",
    price: "৫২০৳",
    oldPrice: "৬৫০৳",
    discount: "20",
    image: "/book_cover_img/book_cover_img (21).webp",
  },
  {
    id: 72,
    title: "আল-মুকাদ্দিমাতুল জাযারিয়্যাহ",
    author: "ইমাম শামসুদ্দীন মুহাম্মাদ ইবনে...",
    price: " ৭৭৳",
    oldPrice: "১৪০৳",
    discount: "45",
    image: "/book_cover_img/book_cover_img (22).webp",
  },
  {
    id: 82,
    title: "বেরেলির ইমাম",
    author: "মাকতাবাতুদ দাওয়াহ টিম",
    price: "২০০৳",
    image: "/book_cover_img/book_cover_img (23).webp",
  },
];
export const authorsData: Author[] = [
  {
    id: 1,
    name: "শায়খ আহমাদুল্লাহ",
    avatar: "/author_Img/author (1).webp",
  },
  {
    id: 2,
    name: "ড. খন্দকার আব্দুল্লাহ জাহা...",
    avatar: "/author_Img/author (2).webp",
  },
  {
    id: 3,
    name: "আরিফ আজাদ",
    avatar: "/author_Img/author (3).webp",
  },
  {
    id: 4,
    name: "ড. আলী মুহাম্মাদ সাল্লাবী",
    avatar: "/author_Img/author (4).webp",
  },
  {
    id: 5,
    name: "মিজানুর রহমান আজহারি",
    avatar: "/author_Img/author (5).webp",
  },
  {
    id: 6,
    name: "ডা. শামসুল আরেফীন",
    avatar: "/author_Img/author (6).webp",
  },
  {
    id: 7,
    name: "ড. রাগিব সারজানী",
    avatar: "/author_Img/author (7).webp",
  },
  {
    id: 8,
    name: "মুহাম্মাদ ইলিয়াস রিফায়ী",
    avatar: "/author_Img/author (1).webp",
  },
];
export const publishersData: Publisher[] = [
  { id: 1, name: "মাকতাবাতুল আযহার", logo: "/brand_logos/wafilife-logo.svg" },
  { id: 2, name: "সিয়ান পাবলিকেশন", logo: "/brand_logos/wafilife-logo.svg" },
  {
    id: 3,
    name: "গার্ডিয়ান পাবলিকেশন্স",
    logo: "/brand_logos/wafilife-logo.svg",
  },
  { id: 4, name: "ওয়াফি পাবলিকেশন", logo: "/brand_logos/wafilife-logo.svg" },
  { id: 5, name: "সমকালীন প্রকাশন", logo: "/brand_logos/wafilife-logo.svg" },
  { id: 6, name: "রুহামা পাবলিকেশন", logo: "/brand_logos/wafilife-logo.svg" },
  { id: 7, name: "পথিক প্রকাশন", logo: "/brand_logos/wafilife-logo.svg" },
  {
    id: 8,
    name: "মুহাম্মাদীয়া লাইব্রেরী",
    logo: "/brand_logos/wafilife-logo.svg",
  },
];
